config/routes.rb
Rails.application.routes.draw do
  root to: "masters#new"

  get "/master/:id/:title", to: "masters#show", as: :master_vanity
  get "/share/:id/:title", to: "shares#show", as: :share_vanity
  get "/preview/:id/:title", to: "previews#show", as: :preview_vanity

  resources :masters, only: [:new, :create, :show, :update, :destroy] do
    resources :items, only: [:create, :destroy, :update]
  end

  resources :previews, only: [:show]

  resources :shares, only: [:show] do
    resources :items, only: [] do
      resource :check, only: [:create, :destroy]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :list
  validates :title, presence: true
end

app/models/list.rb
class List < ApplicationRecord
  before_validation :assign_secrets, on: :create
  validates :share_secret, presence: true, uniqueness: true
  validates :master_secret, presence: true, uniqueness: true
  validates :title, presence: true
  has_many :items, inverse_of: :list, dependent: :delete_all

  def to_param
    raise "Use share_secret or master_secret instead"
  end

  private

  SECRET_LENGTH = 12

  def assign_secrets
    if self.share_secret.present? || self.master_secret.present?
      raise "Invariant: Somehow already has a secret (#{self.attributes}"
    end

    self.share_secret = SecureRandom.alphanumeric(SECRET_LENGTH)
    self.master_secret = SecureRandom.alphanumeric(SECRET_LENGTH)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/checks_controller.rb
class ChecksController < ApplicationController
  def create
    set_checked(true)
  end

  def destroy
    set_checked(false)
  end

  private

  def set_checked(checked_value)
    list = List.find_by(share_secret: params[:share_id])
    item = list.items.find_by(id: params[:item_id])
    item.update!(checked: checked_value)
    redirect_to(share_vanity_path(id: params[:share_id], title: list.title.parameterize))
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def create
    list = List.find_by(master_secret: params[:master_id])
    item_params = params.require(:item).permit(:title)
    item = list.items.build(item_params)
    item.save!
    list.touch
    redirect_to(master_vanity_path(id: list.master_secret, title: list.title.parameterize))
  end

  def update
    list = List.find_by(master_secret: params[:master_id])
    item = list.items.find_by(id: params[:id])
    item_params = params.require(:item).permit(:title)
    item.update!(item_params)
    list.touch
    redirect_to(master_vanity_path(id: list.master_secret, title: list.title.parameterize))
  end

  def destroy
    list = List.find_by(master_secret: params[:master_id])
    item = list.items.find_by(id: params[:id])
    item.destroy!
    list.touch
    redirect_to(master_vanity_path(id: list.master_secret, title: list.title.parameterize))
  end
end

app/controllers/masters_controller.rb
class MastersController < ApplicationController
  def new
    @list = List.new
  end

  def create
    list_params = params.require(:list).permit(:title)
    # TODO handle errors
    list = List.create!(list_params)
    flash[:success] = "Welcome to your new list! Don't lose the link to this page."
    redirect_to(master_vanity_path(id: list.master_secret, title: list.title.parameterize))
  end

  def show
    @list = List.find_by(master_secret: params[:id])
    if @list.nil?
      render inline: "<p>No list found; it may have been deleted by its owner.</p>"
    end
  end

  def update
    list = List.find_by(master_secret: params[:id])
    list_attributes = params.require(:list).permit(:title)
    # TODO handle errors
    list.update!(list_attributes)
    redirect_to(master_vanity_path(id: list.master_secret, title: list.title.parameterize))
  end

  def destroy
    @list = List.find_by(master_secret: params[:id])
    @list.destroy
    redirect_to(root_path)
  end
end

app/controllers/previews_controller.rb
class PreviewsController < ApplicationController
  def show
    # Render a not-found message on `nil`
    @preview = true
    flash.now[:info] = "This is a preview of your list."
    @list = List.where(share_secret: params[:id]).first
    render "shares/show"
  end
end

app/controllers/shares_controller.rb
class SharesController < ApplicationController
  def show
    @preview = false
    # Render a not-found message on `nil`
    @list = List.where(share_secret: params[:id]).first
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wishlist<%= yield(:title).blank? ? "" : sanitize(" | #{yield(:title)}") %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="main-container">
      <div class="main-content container">
        <% flash.each do |key, text| %>
          <div class="row mt-sm-3 alert alert-<%= key %>">
            <%= text %>
          </div>
        <% end %>
        <%= yield %>
      </div>
      <div class="footer container">
        <p class="row pt-sm-3">
          <small><%= link_to "Make your own list", root_path %></small>
          <small class="ml-auto"><%= link_to "Source code", "https://github.com/rmosolgo/wishlist-app" %></small>
        </p>
      </div>
    </div>
  </body>
</html>

app/views/masters/new.html.erb
<% content_for :title, "Make a new list" %>

<h3 class="row mt-sm-3">Wishlist</h3>

<div class="row">
  <p>
    Create a wishlist to share with others.
  </p>

  <p>
    You get a <strong>master link</strong> for managing items,
    and you give the <strong>share link</strong> to others where they can
    (secretly) check them off.
  </p>
</div>

<%= form_for(@list, url: masters_path, html: { class: "row form-inline" }) do |f| %>
  <div class="form-group mr-sm-3">
    <%= f.text_field :title, required: true, placeholder: "Your list's title", class: "form-control" %>
  </div>
  <%= f.submit "Make a list!", class: "btn btn-outline-primary" %>
<% end %>

app/views/masters/show.html.erb
<% content_for :title, "Manage #{@list.title}" %>

<%= form_for(@list, method: :patch, url: master_path(id: @list.master_secret), html: { class: "row mt-sm-3" }) do |f| %>
  <div class="col-10 px-0">
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="col-2 px-0">
    <%= f.submit "Update title", class: "ml-sm-3 btn btn-outline-primary" %>
  </div>
<% end %>

<ul class="row mt-sm-3 list-group">
  <li class="list-group-item">
    <strong>Manage Items</strong>
    <br>
    <span class="text-muted"><em>If you shared this list, some items may have been checked already.</em></span>
  </li>
  <% @list.items.each do |item| %>
    <li class="list-group-item col-12">
      <div class="row">
        <span class="item-option col-10"><%= auto_link(item.title) %></span>
        <%= form_for(item, url: master_item_path(master_id: @list.master_secret, id: item.id), method: :patch, html: { class: "item-option item-option-hidden col-10" }) do |f| %>
          <div class="row">
            <div class="col-10 pl-1 pr-0">
              <%= f.text_field :title, class: "form-control" %>
            </div>
            <div class="col-2 px-0">
              <%= f.submit "Update", class: "btn ml-sm-3 btn-outline-primary" %>
            </div>
          </div>
        <% end %>
        <div class="col-2">
          <%= link_to "✎", "#", onclick: "event.preventDefault(); toggleItemEdit(this.parentNode.parentNode)", class: "btn btn-sm btn-outline-primary float-right" %>
          <%= link_to "x", master_item_path(master_id: @list.master_secret, id: item.id), method: :delete, class: "btn btn-sm btn-outline-danger float-right mx-sm-3", data: { confirm: "Delete \"#{item.title}\"?" } %>
        </div>
      </div>
    </li>
  <% end %>
  <li class="list-group-item">
    <%= form_for(@list.items.build, url: master_items_path(master_id: @list.master_secret), html: { class: "row" }) do |f| %>
      <div class="col-10 pr-0 pl-1">
        <%= f.text_field :title, class: "form-control", autofocus: true %>
      </div>
      <div class="col-2 px-0">
        <%= f.submit "Add Item", class: "btn ml-sm-3 btn-outline-primary" %>
      </div>
    <% end %>
  </li>
</ul>

<ul class="list-group row mt-sm-3">
  <li class="list-group-item">
    <% master_link = master_vanity_url(id: @list.master_secret, title: @list.title.parameterize) %>
    <strong>Master link:</strong> <a href="<%= master_link %>"><code><%= master_link %></code></a>
    <br>
    <em>Anyone</em> with this link can manage items or delete the list. (This link is probably just for you.)
  <br>
    <%= link_to "Copy this link", "#", onclick: "event.preventDefault(); copyToClipboard('#{master_link}'); this.text = 'Copied! Now save it somewhere.'" %>

  </li>

  <li class="list-group-item">
    <% preview_link = preview_vanity_url(id: @list.share_secret, title: @list.title.parameterize) %>
    <strong>Preview link:</strong> <a href="<%= preview_link %>"><code><%= preview_link %></code></a>
    <br>
    This is what your list looks like to others (but this doesn't tell you if anyone checked items!)
  </li>

  <li class="list-group-item">
    <% share_link = share_vanity_url(id: @list.share_secret, title: @list.title.parameterize)%>
    <strong>Share link:</strong> <code><%= share_link %></code>
    <br>
    Anyone with this link may check and uncheck items.
    <br>
    <%= link_to "Copy this link", "#", onclick: "event.preventDefault(); copyToClipboard('#{share_link}'); this.text = 'Copied! Now send it to someone.'" %>
    <br>
    <em>If you visit that link, it will ruin the surprise 😉</em>
  </li>

  <li class="list-group-item">
    <%= link_to "Delete \"#{@list.title}\" forever", master_path(id: @list.master_secret), method: :delete, class: "btn btn-danger", data: { confirm: "Are you sure you want to delete this FOREVER?" } %>
  </li>
</ul>

app/views/shares/show.html.erb
<% if @list.nil? %>
  <p>
    No list here! It might have been deleted by its owner.
  </p>
<% else %>
  <%= content_for :title, @preview ? "PREVIEW #{@list.title}" : @list.title %>
  <h3 class="row mt-sm-3"><%= @list.title %></h3>
  <ul class="list-group row mt-sm-3">
    <% item_order = @preview ? { created_at: :asc } : { checked: :asc, created_at: :asc } %>
    <% @list.items.order(item_order).each do |item| %>
      <li class="list-group-item">
        <% if @preview %>
          <%= check_box_tag "checked", "no_value", false, disabled: true %>
        <% else %>
          <% form_method = item.checked? ? :delete : :post %>
          <%= form_for(item, method: form_method, url: share_item_check_path(share_id: @list.share_secret, item_id: item.id), html: { style: "display: inline;" }) do |f| %>
            <% f.check_box :checked, onclick: "this.parentNode.submit()"%>
          <% end %>
        <% end %>
        <%= auto_link(item.title) %>
      </li>
    <% end %>
  </ul>

  <p class="row mt-3 text-muted">
    Last updated by owner: <%= @list.updated_at.strftime("%B %-d, %Y") %>
  </p>
<% end %>